/** Frozen IPC channel names — do not rename. */
export const IPC_CHANNELS = {
  START_JOB: 'job:start',
  CANCEL_JOB: 'job:cancel',
  JOB_PROGRESS: 'job:progress',
  JOB_COMPLETE: 'job:complete',
  JOB_ERROR: 'job:error',
  GET_JOBS: 'job:get-all',
  GET_JOB: 'job:get',
  GET_JOB_STATUS: 'job:status',
  GET_JOB_RESULT: 'job:result',
  CLEAR_JOBS: 'job:clear',

  ORDER_CREATE: 'order:create',
  ORDER_GET: 'order:get',
  ORDER_LIST: 'order:list',
  ORDER_DASHBOARD: 'order:dashboard',
  ORDER_TRANSITION: 'order:transition',
  ORDER_ATTACH_JOB: 'order:attach-job',
  ORDER_ADD_CONSUMPTION: 'order:add-consumption',

  AUTH_STATE: 'auth:state',
  AUTH_ACTIVATE: 'auth:activate',
  AUTH_LOGIN: 'auth:login',
  ONBOARDING_GET: 'onboarding:get',
  ONBOARDING_STEP: 'onboarding:step',
  ONBOARDING_IDENTITY: 'onboarding:identity',
  ONBOARDING_SLOTS: 'onboarding:slots',
  ONBOARDING_COMPLETE: 'onboarding:complete',
  ADMIN_USERS_LIST: 'admin:users:list',
  ADMIN_USERS_CREATE: 'admin:users:create',
  ADMIN_USERS_PERMISSIONS: 'admin:users:permissions',
  ADMIN_COSTS_GET: 'admin:costs:get',
  ADMIN_MATERIALS_UPSERT: 'admin:materials:upsert',
  ADMIN_CONFIG_GET: 'admin:config:get',
  ADMIN_FORM_SCHEMA: 'admin:form:schema',
  ADMIN_FORM_VALIDATE: 'admin:form:validate',
  ADMIN_DISCIPLINE_SET: 'admin:discipline:set',
  ADMIN_AUDIT_LIST: 'admin:audit:list',
  ADMIN_USERS_DISABLE: 'admin:users:disable',
  ADMIN_USERS_DELETE: 'admin:users:delete',
  ADMIN_USERS_RESET: 'admin:users:reset',
  ADMIN_FIELDS_UPSERT: 'admin:fields:upsert',
  ADMIN_STATUSES_UPDATE: 'admin:statuses:update',
  ADMIN_RESTRICTION: 'admin:restriction',
  ADMIN_WORKSHOP_UI: 'admin:workshop-ui',
  ADMIN_CUSTOMER_UI: 'admin:customer-ui',
  PLATFORM_LOGIN: 'platform:login',
  PLATFORM_TENANTS_LIST: 'platform:tenants:list',
  PLATFORM_TENANT_GET: 'platform:tenant:get',
  PLATFORM_TENANT_BLOCK: 'platform:tenant:block',
  PLATFORM_TENANT_SUSPEND: 'platform:tenant:suspend',
  PLATFORM_TENANT_UNBLOCK: 'platform:tenant:unblock',
  PLATFORM_AUDIT_LIST: 'platform:audit:list',
  CONFIG_DISCIPLINE_UPSERT: 'config:discipline:upsert',
  CONFIG_DISCIPLINE_ENABLE: 'config:discipline:enable',
  CONFIG_SCHEMA_PUBLISH: 'config:schema:publish',
  CONFIG_SCHEMA_ARCHIVE: 'config:schema:archive',
  CONFIG_FIELDS_REORDER: 'config:fields:reorder',
  CONFIG_FIELD_DEACTIVATE: 'config:field:deactivate',
  CONFIG_FORM_GET: 'config:form:get',
  CONFIG_FORM_PREVIEW: 'config:form:preview',
  CONFIG_QUOTE: 'config:quote',
  CONFIG_ORDER_SUBMIT: 'config:order:submit',
  CUSTOMER_REGISTER: 'customer:register',
  CUSTOMER_LOGIN: 'customer:login',
  CUSTOMER_FORM: 'customer:form',
  CUSTOMER_PREVIEW: 'customer:preview',
  CUSTOMER_ATTACH: 'customer:attach',
  CUSTOMER_SUBMIT: 'customer:submit',
  CUSTOMER_LIST: 'customer:list',
  CUSTOMER_GET: 'customer:get',
  CUSTOMER_APPROVE: 'customer:approve',
  CUSTOMER_RUBRICS: 'customer:rubrics',
  CUSTOMER_PRODUCTS: 'customer:products',
  CUSTOMER_META: 'customer:meta',
  CUSTOMER_DRAFT_SAVE: 'customer:draft-save',
  CUSTOMER_DRAFTS: 'customer:drafts',
  CUSTOMER_DRAFT_GET: 'customer:draft-get',
  CUSTOMER_CHANGES: 'customer:changes',
  CUSTOMER_FILE_GET: 'customer:file-get',
  WORKSHOP_ORDERS: 'workshop:orders',
  WORKSHOP_REVISION: 'workshop:revision',
  WORKSHOP_FILE_VERSION: 'workshop:file-version',
  PIPELINE_START: 'pipeline:start',
  PIPELINE_BOARD: 'pipeline:board',
  PIPELINE_DISPATCH: 'pipeline:dispatch',
  PIPELINE_RUN_LOCAL: 'pipeline:run-local',
  PIPELINE_ACK_CLOUD: 'pipeline:ack-cloud',
  PIPELINE_RETRY: 'pipeline:retry',
  PIPELINE_FAIL: 'pipeline:fail',
  PIPELINE_CANCEL_JOB: 'pipeline:cancel-job',
  PIPELINE_CANCEL_PROCESS: 'pipeline:cancel-process',
  PIPELINE_RESUME: 'pipeline:resume',
  CENTER_QUERY: 'production-center:query',
  CENTER_DETAIL: 'production-center:detail',
  CENTER_CALENDAR: 'production-center:calendar',
  CENTER_PRIORITY: 'production-center:priority',
  CENTER_TRANSITION: 'production-center:transition',
  CENTER_START: 'production-center:start',
  CENTER_RETRY: 'production-center:retry',
  CENTER_CANCEL_JOB: 'production-center:cancel-job',
  CENTER_MARK: 'production-center:mark',
  CENTER_ASSIGN: 'production-center:assign',
  CENTER_COMMENT: 'production-center:comment',
  CENTER_FORCE: 'production-center:force',
  CENTER_DUE: 'production-center:due',
  CENTER_FILE: 'production-center:file',
  CENTER_VERSION: 'production-center:version',
  CENTER_STEP_START: 'production-center:step-start',
  CENTER_STEP_COMPLETE: 'production-center:step-complete',
  CENTER_QC: 'production-center:qc',
  CENTER_CANCEL_WORKFLOW: 'production-center:cancel-workflow',
  NOTIFICATIONS_LIST: 'notifications:list',
  NOTIFICATIONS_READ: 'notifications:read',
  ORDER_TIMELINE: 'orders:timeline',
  DEADLINES_EVALUATE: 'ops:evaluate-deadlines',

  GET_SYSTEM_INFO: 'system:info',
  GET_MODELS: 'system:models',
  MODELS_HAS_ANY: 'models:has-any',
  MODELS_DOWNLOAD: 'models:download',
  MODELS_DOWNLOAD_PROGRESS: 'models:download-progress',
  SELECT_DIRECTORY: 'system:select-directory',
  OPEN_OUTPUT_FOLDER: 'system:open-output',

  GET_SETTINGS: 'settings:get',
  UPDATE_SETTINGS: 'settings:update',
  RESET_SETTINGS: 'settings:reset',

  VALIDATE_IMAGE: 'file:validate',
  GET_IMAGE_INFO: 'file:info',
  EXPORT_COPY: 'file:export-copy',
  STAGE_INPUT_IMAGE: 'file:stage-input',
  WRITE_TEMP_INPUT: 'file:write-temp-input',

  PIPELINE_AUDIT: 'debug:pipeline-audit',
  GET_PIPELINE_AUDIT_LOG_PATH: 'debug:pipeline-audit-path',

  APP_READY: 'app:ready',

  APPAREL_GET_CUSTOM_TABLES: 'apparel:custom-tables:get',
  APPAREL_SAVE_CUSTOM_TABLE: 'apparel:custom-table:save',
  APPAREL_EXPORT_CUSTOM_TABLE: 'apparel:custom-table:export',
  APPAREL_IMPORT_CUSTOM_TABLE: 'apparel:custom-table:import',

  APPAREL_GET_MOLD_TEMPLATE_EDITS: 'apparel:mold-templates:get',
  APPAREL_SAVE_MOLD_TEMPLATE_EDIT: 'apparel:mold-template:save',
  APPAREL_EXPORT_MOLD_TEMPLATE: 'apparel:mold-template:export',
  APPAREL_IMPORT_MOLD_TEMPLATE: 'apparel:mold-template:import',

  APPAREL_GET_COLLAR_SELECTIONS: 'apparel:collar-selections:get',
  APPAREL_SAVE_COLLAR_SELECTION: 'apparel:collar-selection:save',

  APPAREL_GET_SLEEVE_SELECTIONS: 'apparel:sleeve-selections:get',
  APPAREL_SAVE_SLEEVE_SELECTION: 'apparel:sleeve-selection:save',

  APPAREL_GET_SEAM_SELECTIONS: 'apparel:seam-selections:get',
  APPAREL_SAVE_SEAM_SELECTION: 'apparel:seam-selection:save',

  APPAREL_GET_FABRIC_SELECTIONS: 'apparel:fabric-selections:get',
  APPAREL_SAVE_FABRIC_SELECTION: 'apparel:fabric-selection:save',

  APPAREL_GET_SUBLIMATION_SELECTIONS: 'apparel:sublimation-selections:get',
  APPAREL_SAVE_SUBLIMATION_SELECTION: 'apparel:sublimation-selection:save',
  APPAREL_GET_SUBLIMATION_ASSETS: 'apparel:sublimation-assets:get',
  APPAREL_IMPORT_VECTOR_GRAPHIC: 'apparel:vector-graphic:import',
  APPAREL_READ_VECTOR_MARKUP: 'apparel:vector-markup:read',
  APPAREL_UPDATE_VECTOR_TEXT: 'apparel:vector-text:update',

  APPAREL_GET_SLOT_STYLES: 'apparel:slot-styles:get',
  APPAREL_SAVE_SLOT_STYLE: 'apparel:slot-style:save',
  APPAREL_AI_PARSE_INSTRUCTION: 'apparel:ai:parse-instruction',

  APPAREL_GET_EGRESADOS_PROJECTS: 'apparel:egresados-projects:get',
  APPAREL_SAVE_EGRESADOS_PROJECT: 'apparel:egresados-project:save',
  APPAREL_CREATE_EGRESADOS_PROJECT: 'apparel:egresados-project:create',

  APPAREL_EXPORT_GARMENT: 'apparel:garment:export',

  APPAREL_MPT_GET_OVERRIDES: 'apparel:mpt-overrides:get',
  APPAREL_MPT_SAVE_OVERRIDE: 'apparel:mpt-override:save',
} as const;
